### PR TITLE
Add scripts on settings page media

### LINKED ISSUE #39: Buttons not working
Nothing happens when I click the buttons on the media settings page.

Wordpress version 4.5.3
Chrome 51.0.2704.103
Mac OS X El Capitan

### PR DESCRIPTION
**Pull request by tobaco**
fix #39

### CODE REVIEW

**Comment by Rahe** [comment]
Hey,

Thank you for the PR, can you use an in_array instead of adding a OR ?

Thank you :)

**Comment by tobaco** [comment]
@Rahe 
better? ;-)

**Comment by Rahe** [comment]
Yes thank you, I will apply the WordPress coding standards after the merge :).

**Comment by tobaco** [comment]
oh, ok. thanks!

**Pull request merged**
